version: "3.6"

services:

  jupyterlab:
    image: jupyterlab
    container_name: jupyterlab
    restart: always
    ports:
      - 8888:8888
    volumes:
      - shared-workspace:/opt/workspace
    networks:
      - localnet
  
  spark-master:
    image: spark-master
    container_name: spark-master
    restart: always
    ports:
      - 8080:8080
      - 7077:7077
    volumes:
      - shared-workspace:/opt/workspace
    networks:
      - localnet

  spark-worker-1:
    image: spark-worker
    container_name: spark-worker-1
    restart: always
    environment:
      SPARK_WORKER_CORES: "1"
      SPARK_WORKER_MEMORY: "2048m"
    ports:
      - 8081:8081
    volumes:
      - shared-workspace:/opt/workspace
    networks:
      - localnet
    depends_on:
      - spark-master

  spark-worker-2:
    image: spark-worker
    container_name: spark-worker-2
    restart: always
    environment:
      SPARK_WORKER_CORES: "1"
      SPARK_WORKER_MEMORY: "2048m"
    ports:
      - 8082:8081
    volumes:
      - shared-workspace:/opt/workspace
    networks:
      - localnet
    depends_on:
      - spark-master

  mongodb2:
    image: mongo:5.0.5
    container_name: mongodb2
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 1234
    ports:
      - "27017:27017"
    volumes:
        - mongodb2:/data/db
        - mongodb_config2:/data/configdb
    networks:
      - localnet


volumes:
  shared-workspace:
    name: "hadoop-distributed-file-system"
    driver: local
  mongodb2:
  mongodb_config2:

networks:
  localnet:
    attachable: true